### ISSUE TITLE
Stingray - Missing Thumbnail

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#30]
The stingray is missing it's thumbnail in-game, after a quick look in the files it looks like it is because the thumbnail image is named stingray and the code is calling for "thumbnail/stingray-thumb". (Reference image below for context.)

![LIM Stingray](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/2cfc3a0d-c999-4b59-a6aa-e071b590bc50)

![LIM Stingray 2](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/cd99a40b-a66a-4946-8a56-4ab2a1c2fbca)

**Comment by MidnightPlugins** [comment]
Thanks for notifying me. The image is included with release. Image is now in repository.

While working on these, it appears that I mistakenly uploaded duplicate ship images instead of thumbnails to the thumbnail folder. I've discovered similar mistakes were made for the Basket-hilts, Heavy Enforcer, Longsword, and Modified Hogshead. Those have been corrected as well.
